### ISSUE TITLE
loop recordings and loop sections of recordings 

### ISSUE THREAD

**Issue by RustoMCSpit** [FossifyOrg/Voice-Recorder#1]
**Describe the solution you'd like**
loop button to loop a recording, a part of a recording, or multiple recordings

**Comment by Aga-C** [comment]
Please adjust your feature request report to the [issue template](https://raw.githubusercontent.com/FossifyOrg/Voice-Recorder/master/.github/ISSUE_TEMPLATE/feature_request.md).

**Comment by Aga-C** [comment]
- Do you mean playback?
- Why it should be in Voice Recorder app? Because if we talk about playback, it sounds more like a job for an app like Music Player.
- If playback, looping a part of the recording is not really related to looping one or multiple recordings. Please create a new feature request for that.

**Comment by inson1** [comment]
https://github.com/SimpleMobileTools/Simple-Voice-Recorder/issues/210
