### ISSUE TITLE
recording should save itself right before phone dies

### ISSUE THREAD

**Issue by RustoMCSpit** [FossifyOrg/Voice-Recorder#5]

**Comment by Aga-C** [comment]
Please adjust your feature request report to the [issue template](https://raw.githubusercontent.com/FossifyOrg/Voice-Recorder/master/.github/ISSUE_TEMPLATE/feature_request.md).

**Comment by RustoMCSpit** [comment]
> Please adjust your feature request report to the [issue template](https://raw.githubusercontent.com/FossifyOrg/Voice-Recorder/master/.github/ISSUE_TEMPLATE/feature_request.md).

it's self-explanatory

**Comment by Aga-C** [comment]
Everyone can tell that their issues are self-explanatory and just ignore the template, and then others will point this issue as an example that template is not required by us. 

At least fill the checklist. Also, you could add, e.g. whether you'd like to have this in settings.

**Comment by inson1** [comment]
https://github.com/SimpleMobileTools/Simple-Voice-Recorder/issues/242

**Comment by naveensingh** [comment]
I think a simpler solution would be to just charge the phone before recording given that most phones will remind you when your battery is low. I'm closing this...

**Comment by RustoMCSpit** [comment]
> I think a simpler solution would be to just charge the phone before recording given that most phones will remind you when your battery is low. I'm closing this...

sometimes theres no charge, life happens and people get unlucky. it's your call but it would make sensw for this to be tagged 'needs help' rather than closed.

**Comment by inson1** [comment]
I would like feature too tbh, things happen 
Why do backups? just dont break it and dont loose it

**Comment by naveensingh** [comment]
@RustoMCSpit all of your issues in this repo are still not formatted according to the issue templates even after we notified you. Seems like you also ignored the following line present in the issue templates:

>  "[ ]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise."

Please consider closing your issues and raising new ones with proper info using the new [issue form options](https://github.com/FossifyOrg/Voice-Recorder/issues/new/choose). Otherwise, I'll probably close your issues simply to enforce the same rules on everyone.

-------

> sometimes theres no charge, life happens and people get unlucky.

Things happen but this is an edge case. Why would you ignore the system warnings to charge your phone? I think this is one of those little things in life that teach us that actions (or lack thereof) have consequences but you are welcome to raise a new feature request with the proper format. I'm not reopening this empty issue. 

> Why do backups? just dont break it and dont loose it

Backups protect against **unpredictable** things like hardware failures, virus attacks, and other disasters. Your phone losing all its charge isn't on the same level and is pretty predictable.

**Comment by Aga-C** [comment]
As mentioned in https://github.com/FossifyOrg/Voice-Recorder/issues/5#issuecomment-1951413763, I am closing all issues with missing templates.

**Comment by HT-7** [comment]
> I think a simpler solution would be to just charge the phone

The whole point of safeguards is to correct for human error.

**Comment by naveensingh** [comment]
Thanks but again, I have to disagree with the analogy here:

> "Why wear a phone case? Just don't drop your phone..."

_Phones usually do not issue **warnings** to put on a case, they just fall._

> "teach them lessons".

There is no "us vs them", I am one of the users.

Anyway, this should already be working as a side effect of https://github.com/FossifyOrg/Voice-Recorder/issues/74.

**Comment by HT-7** [comment]
> Anyway, this should already be working as a side effect of [#74](https://github.com/FossifyOrg/Voice-Recorder/issues/74).

This seems to be the case MP3 and OPUS, but M4A files that were not saved properly have no "moov atom" at the end and require [manual recovery](https://sysfrontier.com/en/2014/12/31/hello-world/).

**Comment by naveensingh** [comment]
> recovering broken recordings

https://github.com/FossifyOrg/Voice-Recorder/issues/87 would require that to be implemented.
