### ISSUE TITLE
mp3 should be the automatic file extension type

### ISSUE THREAD

**Issue by RustoMCSpit** [FossifyOrg/Voice-Recorder#6]
**Describe the solution you'd like**
on first open of the app ask the user to input desired file extension and clarify that m4a isnt foss 

**Describe alternatives you've considered**
just make mp3 the default until flac is integrated / opus is fixed

**Comment by Aga-C** [comment]
Please adjust your feature request report to the [issue template](https://raw.githubusercontent.com/FossifyOrg/Voice-Recorder/master/.github/ISSUE_TEMPLATE/feature_request.md).

**Comment by RustoMCSpit** [comment]
whats needs triage mean?

**Comment by Aga-C** [comment]
This label means: `Issue is not yet ready for PR authors to take up`. We're waiting for the issue template to be filled out properly.

**Comment by RustoMCSpit** [comment]
> This label means: `Issue is not yet ready for PR authors to take up`. We're waiting for the issue template to be filled out properly.

thats pedantic but okay

**Comment by Aga-C** [comment]
@naveensingh Can you check this and decide whether it should be done?

**Comment by inson1** [comment]
https://github.com/SimpleMobileTools/Simple-Voice-Recorder/issues/234

**Comment by naveensingh** [comment]
https://github.com/SimpleMobileTools/Simple-Voice-Recorder/issues/1
https://github.com/SimpleMobileTools/Simple-Voice-Recorder/issues/21
https://github.com/SimpleMobileTools/Simple-Voice-Recorder/issues/62

Support for 'real' MP3 format was added in https://github.com/SimpleMobileTools/Simple-Voice-Recorder/pull/114. I haven't done much work on the Voice Recorder but I think the M4A stayed the default because:
 - Tibor forgot to switch to MP3.
 - Or the MP3 recorder implementation wasn't reliable enough (I remember some chatter related to it)

So we will switch to MP3 but if it causes any problems among the uninitiated users, I'm switching it back to M4A until MP3 works properly.

> honestly this is such an easy fix that it doesnt 'need triage', i imagine youd just change a single variables initial state and it's done

@RustoMCSpit it has nothing to do with easy. In projects like this, one must carefully consider the consequences before changing even a small constant. If we don't, it won't be long before the whole project is a mess that only works properly for a small group of people. When working with SMT, we often broke things even when we were sure we had considered every possible use case.
