### ISSUE TITLE
OggOpus records in 44.1 kHz but marks file as 48 kHz

### ISSUE THREAD

**Issue by RustoMCSpit** [FossifyOrg/Voice-Recorder#8]
I made many recordings with Opus and 320 kbps, and realized they all sound high pitched (and a bit fast). Importing to Audacity and changing the sample rate to 44.1 fixes the problem.

Every audio player I've tried including the Simple Voice Recorder's playback of any recorded files sounds high-pitched.

It seems that the Ogg encoder the player uses encodes (or marks) the files as 48 kHz whereas they are being exported as 44.1 kHz.

The M4A setting does not have this problem, but I like Opus and very happy to see this program supports it.

**Comment by Aga-C** [comment]
Please adjust your bug report to the [issue template](https://raw.githubusercontent.com/FossifyOrg/Voice-Recorder/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by TheRupp** [comment]
More about the same problem:
- [https://github.com/SimpleMobileTools/Simple-Voice-Recorder/issues/102](url)
- [https://github.com/SimpleMobileTools/Simple-Voice-Recorder/issues/164](url)
- [https://github.com/SimpleMobileTools/Simple-Voice-Recorder/issues/228](url)

1 other way to prove this problem:
I created an audio recording with the app and looked at the time shown in the "Recorder" tab (I checked this time with another clock. This time is correct.) (for example 1:40 minutes = 100 seconds). The newly created audio file has a different duration (in the same example with 100 seconds this was NOT 100 seconds, but 1:32 minutes = 92 seconds). This time difference is 92 s/100 s = 92 %, which could be 44.1 kHz / 48 kHz = 91,875 %.
This problem does not happen with other file formats other that OPUS/.ogg.

This problem was important enough for me that I switched to a different app. I really wanted to record with OPUS.

**Comment by David-Else** [comment]
This is a massive bug making the app unusable for anyone who wants to actually use the recordings for anything meaningful, please could @Aga-C say why was is closed? Thanks :)

**Comment by Aga-C** [comment]
@David-Else This issue has been closed during clean-up of wrongly reported issues. If you'd like, you can raise it once again, properly.

**Comment by RustoMCSpit** [comment]
> This is a massive bug making the app unusable for anyone who wants to actually use the recordings for anything meaningful, please could @Aga-C say why it is closed? Thanks :)

one sec i'll do it for you

**Comment by RustoMCSpit** [comment]
> @David-Else This issue has been closed during clean-up of wrongly reported issues. If you'd like, you can raise it once again, properly.

https://github.com/FossifyOrg/Voice-Recorder/issues/32
